change in cloudbuild1.yaml

diff --git a/cloudbuild1.yaml b/cloudbuild1.yaml
--- a/cloudbuild1.yaml
+++ b/cloudbuild1.yaml
@@ -26,7 +26,21 @@ steps:
         ls -la /workspace/repo
     id: 'Verify Repo Structure'
 
-  # Step 3: Build Docker Image with necessary tools and libraries for Cucumber
+  # Step 3: Verify presence of package.json in /workspace/repo
+  - name: 'alpine'
+    entrypoint: 'sh'
+    args:
+      - '-c'
+      - |
+        if [ -f /workspace/repo/package.json ]; then
+          echo "package.json found in /workspace/repo."
+        else
+          echo "package.json not found in /workspace/repo. Exiting."
+          exit 1
+        fi
+    id: 'Check package.json Presence'
+
+  # Step 4: Build Docker Image with necessary tools and libraries for Cucumber
   - name: 'gcr.io/cloud-builders/docker'
     args: [
       'build',
@@ -36,7 +50,7 @@ steps:
     ]
     id: 'Build Docker Image'
 
-  # Step 4: Run Cucumber tests inside the Docker container
+  # Step 5: Run Cucumber tests inside the Docker container
   - name: 'gcr.io/$PROJECT_ID/playwright-cucumber'  # Use the image built in the previous step
     entrypoint: 'bash'
     args:
@@ -63,7 +77,7 @@ steps:
       - 'ls -la /workspace && ls -la /workspace/cucumber-report && chmod -R 777 /workspace/cucumber-report && chown -R root:root /workspace/cucumber-report'
     id: 'Debug Cucumber Report Directory'
 
-  # Step 5: Generate Cucumber HTML Report
+  # Step 6: Generate Cucumber HTML Report
   # Assuming you use a report generator like cucumber-html-reporter in your Docker container
   - name: 'gcr.io/$PROJECT_ID/playwright-cucumber'
     entrypoint: 'bash'
@@ -73,7 +87,7 @@ steps:
         npx cucumber-html-reporter --inputDir /workspace/repo/cucumber-json --output /workspace/cucumber-report  # Adjust command based on your setup
     id: 'Generate Cucumber Report'
 
-  # Step 6: Upload Cucumber Report to GCS
+  # Step 7: Upload Cucumber Report to GCS
   - name: 'gcr.io/cloud-builders/gsutil'
     args:
       - '-m'
